import{S as y,a as g,i as h}from"./assets/vendor-BjRz3xa9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();document.querySelector(".next-page-btn");function b(r){const e=r.map(({webformatURL:o,largeImageURL:i,tags:t,likes:s,views:a,comments:m,downloads:f})=>`<li class="gallery-item">
      <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${o}" alt="${t}"/>
    <ul class="description">
    <li class="descr-item"><p class="descr-item-title">Likes</p><p class="descr-item-value">${s}</p></li>
    <li class="descr-item"><p class="descr-item-title">Views</p><p class="descr-item-value">${a}</p></li>
    <li class="descr-item"><p class="descr-item-title">Comments</p><p class="descr-item-value">${m}</p></li>
    <li class="descr-item"><p class="descr-item-title">Downloads</p><p class="descr-item-value">${f}</p></li>
    </ul></a>
    </li>
    `).join("");u(e)}function u(r=""){const e=document.querySelector(".gallery");e.innerHTML=r,r&&$()}function $(){new y(".gallery a",{captionData:"alt",captionDelay:250,overlayOpacity:.8}).refresh()}function p(r){const e=document.querySelector(".loader");e.style.display=r}const v="49624425-89d18311d8423019c2709bd63",L=document.querySelector(".js-name-input"),S=document.querySelector(".next-page-btn"),q=document.querySelector(".js-form");let l=1,n=0;async function w(r){try{const e=await g(`https://pixabay.com/api/?key=${v}&q=${L.value}&image_type=photo&orientation=horizontal&safesearch=true&per_page=115&page=${l}`);if(n=e.data.totalHits,console.log(n),console.log(e.data),!e.data.hits.length)return c("Sorry, there are no images matching your search query. Please try again!","#ef4040"),q.reset(),e.data.hits;b(e.data.hits),l+=1,l>1&&(S.display="block");const o=e.data.hits}catch(e){c(e.message,"#ef4040")}finally{p("none")}}function c(r,e){h.show({title:`${r}`,backgroundColor:`${e}`,titleColor:"#fff",titleSize:"16px",position:"topRight"})}const d=document.querySelector(".js-form");d.addEventListener("submit",x);function x(r){if(r.preventDefault(),!this.elements["search-text"].value.trim()){d.reset(),c("Enter correct data, please","#ef4040");return}u(),p("block"),w()}
//# sourceMappingURL=index.js.map
