import{S as L,a as S,i as v}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();function w(r){const t=r.map(({webformatURL:n,largeImageURL:i,tags:e,likes:s,views:l,comments:h,downloads:b})=>`<li class="gallery-item">
      <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${n}" alt="${e}"/>
    <ul class="description">
    <li class="descr-item"><p class="descr-item-title">Likes</p><p class="descr-item-value">${s}</p></li>
    <li class="descr-item"><p class="descr-item-title">Views</p><p class="descr-item-value">${l}</p></li>
    <li class="descr-item"><p class="descr-item-title">Comments</p><p class="descr-item-value">${h}</p></li>
    <li class="descr-item"><p class="descr-item-title">Downloads</p><p class="descr-item-value">${b}</p></li>
    </ul></a>
    </li>
    `).join("");p(t)}function p(r=""){document.querySelector(".gallery").insertAdjacentHTML("beforeend",r),r&&$()}function $(){new L(".gallery a",{captionData:"alt",captionDelay:250,overlayOpacity:.8}).refresh()}function y(r){const t=document.querySelector(".loader");t.style.display=r}const q="49624425-89d18311d8423019c2709bd63",x=document.querySelector(".js-name-input"),u=document.querySelector(".next-page-btn"),P=document.getElementById("imageCount"),I=document.querySelector(".js-form");let o=1,a=0;const d=15;async function f(r){try{const t=await S(`https://pixabay.com/api/?key=${q}&q=${x.value}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${d}&page=${o}`);if(a=t.data.totalHits,P.textContent=a,console.log(a),!t.data.hits.length)return c("Sorry, there are no images matching your search query. Please try again!","#ef4040"),I.reset(),u.style.display="none",t.data.hits;if(w(t.data.hits),o+=1,o>1&&(u.style.display="block"),o>2){const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*3,left:0,behavior:"smooth"})}o>Math.ceil(a/d)&&(u.style.display="none",c("That's all images.","#e76f6f"),o=1);const n=t.data.hits}catch(t){c(t.message,"#ef4040")}finally{y("none")}}function O(){o=1;const r=document.querySelector(".gallery");r.innerHTML=""}function c(r,t){v.show({title:`${r}`,backgroundColor:`${t}`,titleColor:"#fff",titleSize:"16px",position:"topRight",iconURL:"./Group (1).svg"})}const g=document.querySelector(".js-form");g.addEventListener("submit",C);const B=document.querySelector(".next-page-btn");let m="";function C(r){if(r.preventDefault(),O(),m=this.elements["search-text"].value.trim(),!m){g.reset(),c("Enter correct data, please","#ef4040");return}f(),p(),y("block")}B.addEventListener("click",f);
//# sourceMappingURL=index.js.map
