import{S,a as v,i as w}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();function L(r){const t=r.map(({webformatURL:a,largeImageURL:i,tags:e,likes:s,views:l,comments:h,downloads:b})=>`<li class="gallery-item">
      <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${a}" alt="${e}"/>
    <ul class="description">
    <li class="descr-item"><p class="descr-item-title">Likes</p><p class="descr-item-value">${s}</p></li>
    <li class="descr-item"><p class="descr-item-title">Views</p><p class="descr-item-value">${l}</p></li>
    <li class="descr-item"><p class="descr-item-title">Comments</p><p class="descr-item-value">${h}</p></li>
    <li class="descr-item"><p class="descr-item-title">Downloads</p><p class="descr-item-value">${b}</p></li>
    </ul></a>
    </li>
    `).join("");p(t)}function p(r=""){document.querySelector(".gallery").insertAdjacentHTML("beforeend",r),r&&$()}function $(){new S(".gallery a",{captionData:"alt",captionDelay:250,overlayOpacity:.8}).refresh()}function f(r){const t=document.querySelector(".loader");t.style.display=r}const q="49624425-89d18311d8423019c2709bd63",x=document.querySelector(".js-name-input"),u=document.querySelector(".next-page-btn"),P=document.querySelector(".js-form");let o=1,c=0;const d=15;async function y(r){try{const t=await v(`https://pixabay.com/api/?key=${q}&q=${x.value}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${d}&page=${o}`);if(c=t.data.totalHits,console.log(c),!t.data.hits.length)return n("Sorry, there are no images matching your search query. Please try again!","#ef4040"),P.reset(),t.data.hits;if(L(t.data.hits),o+=1,o>1&&(u.style.display="block"),o>2){const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*3,left:0,behavior:"smooth"})}o>Math.ceil(c/d)&&(u.style.display="none",n("We're sorry, but you've reached the end of search results.","#ef4040"),o=1);const a=t.data.hits}catch(t){n(t.message,"#ef4040")}finally{f("none")}}function O(){o=1;const r=document.querySelector(".gallery");r.innerHTML=""}function n(r,t){w.show({title:`${r}`,backgroundColor:`${t}`,titleColor:"#fff",titleSize:"16px",position:"topRight"})}const g=document.querySelector(".js-form");g.addEventListener("submit",M);const I=document.querySelector(".next-page-btn");let m="";function M(r){if(r.preventDefault(),O(),m=this.elements["search-text"].value.trim(),!m){g.reset(),n("Enter correct data, please","#ef4040");return}y(),p(),f("block")}I.addEventListener("click",y);
//# sourceMappingURL=index.js.map
